add ansible-lint actions
HPCSLab/infra pull request #19
Opened 2024-11-12 05:52 UTC by onokatio

2024-11-12 05:54 UTC, onokatio commented
lintが落ちていますが想定内なので一旦マージしてください。

2024-11-12 06:32 UTC, namachan10777 approved these changes
Ansibleはuvで管理しているからansible-lintもuvで実行してほしい

2024-11-12 06:33 UTC, namachan10777 commented
間違えて承認しちゃった

2024-11-13 05:43 UTC, onokatio commented
uvでansible-lintを入れるようにした

2024-11-13 05:45 UTC, namachan10777 requested changes

2024-11-13 05:45 UTC, namachan10777 commented on .github/workflows/ansible-lint.yml
> +      - name: Setup venv
```
uv sync
uv run
```
でいける

2024-11-13 05:49 UTC, namachan10777 approved these changes
thx!

2024-11-13 05:49 UTC, merged